os: linux
dist: xenial
language: python
python:
        - 3.8
before_install:
        - pip install poetry
install:
        - poetry install
script:
        - python -m doctest pyfunctory/*.py
        - poetry run pytest -s --cov=pyfunctory ./tests
        - poetry run flake8 pyfunctory/
        - poetry run black --check pyfunctory/
after_success:
        - codecov
